name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    name: "Deploy to ITAS WMD server"
    runs-on: self-hosted
    env:
      PORT: 40514
    steps:
      - name: Copy source code files
        uses: actions/checkout@master
      - name: Test files are visibile
        run: |
            whoami
            ls -lah
