name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    name: "Deploy to ITAS WMD server"
    runs-on: self-hosted
    steps:
      - name: Copy source code files
        uses: actions/checkout@master
      - name: Test files are visibile
        run: |
            whoami
            ls-lah
      - name: Deploy to ITAS WMD server
        run: |
          ssh user@itas-wmd-server
