name: Node GOAT Assignment 1

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches: ["master", "main"]
  schedule:
    - cron: '20 17 * * *' 
  
jobs:
  semgrep:
    name: semgrep/ci 
    runs-on: self-hosted
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v3
      - run: semgrep --sarif --output semgrep-sast.sarif --config "p/default"

  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: katkat055/itas276-nodegoat-kg:latest

  security:
    runs-on: self-hosted
    steps:
      - name: Run Snyk to check Docker images for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: katkat055/itas276-nodegoat-kg
          args: --severity-threshold=high

  SAST-Semgrep:
    runs-on: self-hosted
    container:
      image: returntocorp/semgrep
    steps:
      - name: clone application source code
        uses: actions/checkout@v3
      - name: full semgrep scan
        run: | 
          semgrep --sarif --output semgrep-sast.sarif --config "p/default"
      - name: save report as pipeline artifact
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-sast.sarif
          path: semgrep-sast.sarif
